MvcNews/Entities/NewsCategoryModel.cs
using System;
using System.Collections.Generic;
using MongoDB.Bson;

namespace MvcNews.Entities
{
    public class NewsCategoryModel
    {

        public ObjectId Id { get; set; }

        public string CategoryName { get; set; }

        public ICollection<NewsModel> News { get; set; }

    }
}

MvcNews/Entities/NewsModel.cs
using System;
using MongoDB.Bson;
using System.ComponentModel.DataAnnotations;
using MongoDB.Driver;

namespace MvcNews.Entities
{
    public class NewsModel
    {
        public ObjectId Id { get; set; }

        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        public DateTime PubDate { get; set; }

        public MongoDBRef Category { get; set; }


    }
}

MvcNews/Controllers/NewsCategoryController.cs
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.Builders;
using MvcNews.Entities;

namespace MvcNews.Controllers
{
    public class NewsCategoryController : Controller
    {
        private MongoCollection<NewsCategoryModel> categories = MongoDbContext.GetCollection<NewsCategoryModel>("newscategories");

        //
        // GET: /NewsCategory/

        public ActionResult Index()
        {
            var models = categories.FindAll();
            return View(models);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NewsCategoryModel model)
        {
            try
            {
                categories.Insert(model);
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }

        public ActionResult Edit(string id)
        {
            var model = categories.FindOneById(new ObjectId(id));
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(string id, NewsCategoryModel model)
        {
            try
            {
                var category = categories.FindOneById(new ObjectId(id));
                TryUpdateModel(category);
                categories.Save(category);
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }

        public ActionResult Details(string id)
        {
            var model = categories.FindOneById(new ObjectId(id));
            return View(model);
        }

        public ActionResult Delete(string id)
        {
            var model = categories.FindOneById(new ObjectId(id));
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(string id, NewsCategoryModel o)
        {
            var model = categories.FindAndRemove(Query.EQ("_id", ObjectId.Parse(id)), SortBy.Null);
            //return View(model);
            return RedirectToAction("Index");
        }
    }
}

MvcNews/Controllers/NewsController.cs
using System;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using MvcNews.Entities;
using MongoDB.Driver.Builders;
using System.Collections.Generic;

namespace MvcNews.Controllers
{
    public class NewsController : Controller
    {
        private MongoCollection<NewsCategoryModel> categories = MongoDbContext.GetCollection<NewsCategoryModel>("newscategories");
        private MongoCollection<NewsModel> news = MongoDbContext.GetCollection<NewsModel>("news");

        //
        // GET: /Home/

        public ActionResult Index(int p = 1)
        {
            if (!news.IndexExists(IndexKeys.Descending("PubDate")))
            {
                news.CreateIndex(IndexKeys.Descending("PubDate"));
            }

            var pageSize = 20;
            var skipCount = (p - 1) * pageSize;
            var models = news.Find(Query.Matches("Title", new BsonRegularExpression("e_")));

            models.SetSkip(skipCount);
            models.SetLimit(pageSize);
            models.SetSortOrder(SortBy.Descending("PubDate"));

            var count = models.Count();

            ViewBag.Count = count;
            ViewBag.PageCount = count / pageSize + ((count % pageSize > 0) ? 1 : 0);
            ViewBag.CurrentIndex = p;
            
            return View(models);
        }

        public ActionResult Create()
        {
            var categoriesList = categories.FindAll();

            ViewBag.categories = new SelectList(categoriesList, "Id", "CategoryName");

            var news = new NewsModel()
            {
                PubDate = DateTime.Now
            };
            return View(news);
        }

        [HttpPost]
        public ActionResult Create(NewsModel model, string categoryId)
        {
            try
            {
                model.Category = new MongoDBRef("newscategories", BsonValue.Create(categoryId));

                news.Insert(model);
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
                //return View(model);
            }
        }

        public ActionResult Edit(string id)
        {
            var model = news.FindOneById(new ObjectId(id));
            var categoriesList = categories.FindAll();

            ViewBag.categories = new SelectList(categoriesList, "Id", "CategoryName", model.Category != null ? model.Category.Id.AsString : null);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(string id, string categoryId)
        {
            try
            {
                var newss = news.FindOneById(new ObjectId(id));
                TryUpdateModel(newss);

                newss.Category = new MongoDBRef("newscategories", BsonValue.Create(categoryId));

                news.Save(newss);
                return RedirectToAction("Index");
            }
            catch
            {
                throw;
            }
        }

        public ActionResult Details(string id)
        {
            var model = news.FindOneById(new ObjectId(id));
            return View(model);
        }

        public ActionResult Delete(string id)
        {
            var model = news.FindOneById(new ObjectId(id));
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(string id, NewsCategoryModel o)
        {
            var model = news.FindAndRemove(Query.EQ("_id", ObjectId.Parse(id)), SortBy.Null);
            //return View(model);
            return RedirectToAction("Index");
        }

        public ActionResult InsertBatch()
        {

            var count = 1000000;
            var newsList = new List<NewsModel>(count);
            for (int i = 0; i < count; i++)
            {
                var n = new NewsModel()
                {
                    Id = ObjectId.GenerateNewId(),
                    Content = string.Format("g_content_{0}", i + 1),
                    PubDate = DateTime.Now,
                    Title = string.Format("g_title_{0}", i + 1),

                    //Category = new MongoDBRef("newscategories", categories.FindOne().Id)
                };
                newsList.Add(n);
            }

            news.InsertBatch(newsList);
            
            return Content("ok");

        }
    }
}

MvcNews/Views/News/Create.cshtml
@model MvcNews.Entities.NewsModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>NewsModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", ViewBag.categories as IEnumerable<SelectListItem>)
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PubDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PubDate)
            @Html.ValidationMessageFor(model => model.PubDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcNews/Views/News/Delete.cshtml
@model MvcNews.Entities.NewsModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>NewsModel</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>

    <div class="display-label">PubDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PubDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcNews/Views/News/Details.cshtml
@model MvcNews.Entities.NewsModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>NewsModel</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>

    <div class="display-label">PubDate</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PubDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcNews/Views/News/Edit.cshtml
@model MvcNews.Entities.NewsModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>NewsModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", ViewBag.categories as IEnumerable<SelectListItem>)
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PubDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PubDate)
            @Html.ValidationMessageFor(model => model.PubDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcNews/Views/News/Index.cshtml
@model IEnumerable<MvcNews.Entities.NewsModel>
@{
    ViewBag.Title = "Index";
}
<h2>
    Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink("Go To Categories", "Index", "NewsCategory")
</p>
<table>
    <tr>
        <th>
            Title
        </th>
        <th>
            Content
        </th>
        <th>
            Category
        </th>
        <th>
            PubDate
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Category.Id.AsString)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PubDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
    <tfoot>
        <tr>
            <td colspan="5">
                <div style="text-align: center; margin: 20px 0;">
                    <ul class="paging">
                        <li class="p"><a href="?p=1">1</a></li>
                        @for (int i = (int)ViewBag.CurrentIndex; i <= (int)ViewBag.CurrentIndex + (20); i++)
                        {
                            <li class="p"><a href="?p=@i">@i</a></li>
                        }
                        <li class="p"><a href="?p=@ViewBag.PageCount">@ViewBag.PageCount</a></li>
                        <li>PageCount:@ViewBag.PageCount RowsCount:@ViewBag.Count</li>
                    </ul>
                </div>
            </td>
        </tr>
    </tfoot>
</table>

MvcNews/Views/NewsCategory/Create.cshtml
@model MvcNews.Entities.NewsCategoryModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>NewsCategoryModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryName)
            @Html.ValidationMessageFor(model => model.CategoryName)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcNews/Views/NewsCategory/Delete.cshtml
@model MvcNews.Entities.NewsCategoryModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>NewsCategoryModel</legend>

    <div class="display-label">CategoryName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcNews/Views/NewsCategory/Details.cshtml
@model MvcNews.Entities.NewsCategoryModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>NewsCategoryModel</legend>

    <div class="display-label">CategoryName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MvcNews/Views/NewsCategory/Edit.cshtml
@model MvcNews.Entities.NewsCategoryModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>NewsCategoryModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryName)
            @Html.ValidationMessageFor(model => model.CategoryName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcNews/Views/NewsCategory/Index.cshtml
@model IEnumerable<MvcNews.Entities.NewsCategoryModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink("Back To News", "Index", "News")
</p>
<table>
    <tr>
        <th>
            CategoryName
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

MvcNews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>